version: "3"
services:
  awf:
    image: awf.environment
    build:
      context: .
    command: go run main.go
  test-awf:
    image: awf.environment
    build:
      context: .
    command: go test ./...